server:
  port: 8089

spring:
  datasource:
    url: jdbc:mariadb://nas.codegurus.co.kr:28336/steamworks
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: test12!@QW
  jpa:
    show-sql: true
#logging.level.org.hibernate.type.descriptor.sql: trace
